### ISSUE TITLE
examples: move outside of repo

### ISSUE THREAD

**Issue by iamclaytonray** [graph-gophers/graphql-go#179]
Since this pkg now belongs to an org, I think it makes the most sense to have a `graph-gophers/examples` repo that can be maintained separately. Thoughts?

**Comment by shurcooL** [comment]
If you're going to do that, `example` might be a better name for the repo. E.g., see https://github.com/golang/example and https://dmitri.shuralyov.com/idiomatic-go#use-singular-form-for-collection-repo-folder-name.

**Comment by iamclaytonray** [comment]
I think that's outside the scope of Golang, though, right? Either way, I'm open to whatever 😄

**Comment by shurcooL** [comment]
I just meant that the repo should be called `example` rather than `examples`, that's all.

**Comment by iamclaytonray** [comment]
I'm fine with that 😄

**Comment by deltaskelta** [comment]
I think @tonyghita mentioned that he would prefer to keep the stock starwars example and then have community examples linked to in the readme instead of adding examples to the org. That way you can change and modify your own example without making a PR.

Also, since there are API changes planned for the near future, it may be hard for the org to deal with the added responsibility of maintaining and updating all the examples so that they remain correct.

**Comment by tonyghita** [comment]
Closing this for now. If you have an example repository, please send a PR to get it linked from our README.
