### ISSUE TITLE
Is there a way to override __typename?

### ISSUE THREAD

**Issue by emwalker** [graph-gophers/graphql-go#211]
I would like the ability to specify a resolver for `__typename` similarly to other resolvers.  Is there a way to do this?  If not, is this a feature that can be added?

Use case:  I've found `graphql-go` to be useful for parsing a GraphQL query and translating it to a query in a similar query language ([Dgraph](https://docs.dgraph.io/master/query-language/)).  I do this using code in the resolvers, and after execution I discard the result from `graphql-go`.  Right now it seems that `__typename` is handled as a special case and can only be found in the result.  But for a proper translation to the target language, I'll need to be able to specify a resolver for `__typename` as I have other fields.

**Comment by pavelnikolov** [comment]
Hi @emwalker,

I know that this issue is a bit old... AFAIK, this is not supported. Why do you want to override a special type in GraphQL? Can't you have the same type names in both the GraphQL schema and the Dgraph schema? Ideally, I would like this library to be agnostic of the underlying datasource(s). I am closing this issue as it is not directly related to the library. 
Out of curiosity, do other libraries provide you with a `__typeresolver` or have you found a better workaround?

**Comment by emwalker** [comment]
Hi @pavelnikolov — no problem.  It's been a while since I was looking at this.  Going from memory, Dgraph might not have provided a `__typename`, or the value that it was providing made some assumptions that didn't work for my use case.

Dgraph uses its own adaptation of GraphQL that it calls GraphQL+-, and there are a few incompatibilities with GraphQL.  At the time, I was attempting to create an intermediate layer that would emit genuine GraphQL that a Relay client could consume without issues.  I believe it's possible in some cases to specify the (equivalent of the) `__typename` at the library layer, as in the case of `graphql-ruby`, which provides a hook to [resolve the type](https://graphql-ruby.org/schema/definition.html) (in Ruby).

But I'm not pitching for providing this ability in this library any more, as I'm not currently working on that project at this time.
