### ISSUE TITLE
apollo failed to parse a valid graphql-go schema

### ISSUE THREAD

**Issue by jeffwillette** [graph-gophers/graphql-go#235]
I was trying to codegen some things and I noticed that apollo was failing to parse my valid graphql-go schema because one of my Query definitions had empty args...

this parsed valid and introspected valid from the graphql-go server, but apollo failed to parse the file directly. 

```
type Query {
   foo(): Foo
}
```

In order to fix it I needed to eliminate the brackets, which makes it valid in both parsers

```
type Query {
  foo: Foo
}
```

I am not sure which lib has it correct according to the graphql specs, but I just wanted to bring it to someones attention. Feel free to close if this is a non-issue

**Comment by MaxInertia** [comment]
As far as I can tell the graphql spec doesn't mention support for the former syntax, only the latter.

Relevant section: https://graphql.github.io/graphql-spec/draft/#sec-Field-Arguments

Allowing syntax not in the spec might be undesirable as it can cause problems when switching between graphql libraries. In this case switching from graphql-go to something like apollo, since graphql-go is more lenient. That is assuming this hasn't changed in the last year!
