### ISSUE TITLE
schema should load only those with suffix .graphql?

### ISSUE THREAD

**Issue by u007** [graph-gophers/graphql-go#284]
hi,

is it possible to limit 
```
graphql.MustParseSchema(schema.GetRootSchema(), &resolver.Resolver{})
```
to only load file with extensions *.graphql?

im wondering if it also loads .go files as i can see schema/bindata.go and schema/bindata.go

im planning to add README.md into the directory schema...

thank you

**Comment by hampusohlsson** [comment]
@u007 Go-bindata allows you to ignore files, so you can supply a regex like `-ignore=\.go` to ignore go files. Unfortunately golang doesn't support negative lookahead/behind, so it's hard to write a regex that ignores anything but `.graphql` files. 

But since go-bindata only compiles assets, you can define your `GetRootSchema()` function anyway you want. For example

```go
func GetRootSchema() string {
	buf := bytes.Buffer{}
	for _, name := range AssetNames() {
                // Ignore files without .graphql extension
		if match, _ := regexp.MatchString(`\w+\.graphql$`, name); !match {
			continue
		}
		b := MustAsset(name)
		buf.Write(b)
		if len(b) > 0 && b[len(b)-1] != '\n' {
			buf.WriteByte('\n')
		}
	}
	return buf.String()
}
```

**Comment by pavelnikolov** [comment]
Hi, I don't think that this is an issue with the library. As @hampusohlsson has pointed out how you load the data is up to you. The schema is agnostic of whether you use a file/go-bindata/data store etc.
