### ISSUE TITLE
Getting error for string based descriptions

### ISSUE THREAD

**Issue by deltaskelta** [graph-gophers/graphql-go#294]
I saw #269 got merged and switched my graphql file to use strings but now I get an error when it tries to parse... Is there something I am missing?

```
	schema := graphql.MustParseSchema(s, app.New(DB))
```

```
graphql: syntax error: unexpected "\"\"", expecting Ident (line 6, column 1)
```

**Comment by deltaskelta** [comment]
I see now that I have to call the schema option for that. Shouldn't we be accepting string descriptions by default since that is the default in the spec?

**Comment by pavelnikolov** [comment]
All new features should be opt-in, rather than pushed by default upon upgrade. You have to make a conscious decision that you want to include that feature in your project. Maybe after some time, some features can become the default. I'll close this issue now. Maybe I need to create another issue for improving the documentation... 🤔
