### ISSUE TITLE
Determine query types before resolving

### ISSUE THREAD

**Issue by blakeandrewwood** [graph-gophers/graphql-go#337]
Curious if anyone could point me in the right direction to determine the types being queried in a request before handling and resolving? I understand this might require calling one of the packages underneath the hood, but not sure where to look.

I am creating a gateway service that sits in front of an older graphql service written in PHP. If any types from the older service are queried, I'd like to proxy the request to the older service.

Thanks.

**Comment by pavelnikolov** [comment]
Hi @blakeandrewwood,
unfortunately this is not a feature that we currently support. You might be looking for something like [Apollo GraphQL Federation](https://blog.apollographql.com/apollo-federation-f260cf525d21). 
In order to achieve this you might need to fork and change the internals of this library.

There has been issues(requests) and at least one PR in the past which allow you to see the requested fields.
Federation (formerly known as "schema stitching") is something that I am interested in and PRs would be welcomed.
