### ISSUE TITLE
get query Operation  private to public

### ISSUE THREAD

**Issue by zhaogaolong** [graph-gophers/graphql-go#346]
I want get graphql query operation name, use it  add my prometheus metrics monitor.

metrics items:

```shell
graphql_query_mutation_method_total{method="clusters",service="medusa",type="QUERY"} 338
graphql_query_mutation_method_total{method="delApp",service="medusa",type="MUTATION"} 1
graphql_query_mutation_method_total{method="delDeploy",service="medusa",type="MUTATION"} 14

```
but i can't  get query operation, becuase is a private func. so i make patch to graphql.go
>https://github.com/graph-gophers/graphql-go/blob/master/graphql.go#L221

```go
func (ms *MySchema) Exec(ctx context.Context, queryString string, operationName string, variables map[string]interface{}) (*Response, *query.Operation) {
...
}

func GetOperationMetrics(op *query.Operation) map[string]string {
	result := map[string]string{}
	if op == nil || len(op.Selections) < 1 {
		return result
	}

	filed, _ := op.Selections[0].(*query.Field)
	result["type"] = string(op.Type)
	result["method"] = filed.Name.Name
	result["alias"] = filed.Name.Name
	return result
}

```
is not good Solution，if provide get query.Operation well better.

**Comment by pavelnikolov** [comment]
Where do you want to add the metrics exactly? Do you want to be able to define your own callback function before/after resolvers? I am not sure I understand how you want to use getOperationName exactly and why you need it to be public. Can you be more specific how you want ot use it?

**Comment by zhaogaolong** [comment]
I need Prometheus to monitor graphql mutation and query's interface status and call count.
> https://github.com/prometheus/client_golang

so want get operations. do you know my meaning?

I want graphql interface monitor solution，if have better monitor solution, i want it.

**Comment by pavelnikolov** [comment]
Yes I am familiar with Prometheus and it's Go client. Did you mean that you would like the library to expose prometheus metrics? Or to give you some kind of a callback in which you can increase a counter, for example?
I understand that you want to expose metrics and this is nice. Ideally, I want this to be opt-in feature and the library to be agnostic. Therefore, I would like to know more about your use case.

**Comment by zhaogaolong** [comment]
hi: @pavelnikolov 
   I make a demo  project [graphql-metrics](https://github.com/zhaogaolong/graphql-metrics). 

Important code at : https://github.com/zhaogaolong/graphql-metrics/blob/master/graphql/handler.go#L38 update graphql query and mutation call  count。

I patch up mySchema in `github.com/graph-gophers/graphql-go/graphql.go` , For more information, see  [patch](https://github.com/zhaogaolong/graphql-metrics/blob/master/patch/graphql_patch.sh)

**Comment by zhaogaolong** [comment]
hi: @pavelnikolov 
   do you saw my demo project and have question ? No reply was received from you.

**Comment by zhukaiqiang** [comment]
最近我也面临这个问题，我需要获取到我具体的查询对象

**Comment by zhukaiqiang** [comment]
I have been facing this problem recently, and I need to get my specific query object

**Comment by pavelnikolov** [comment]
@zhaogaolong I did see your project and I'll think about it a bit more before making changes. Your patch to the `Exec` method is a breaking change. So it is absolutely unacceptable. Such a feature should be opt-in only. 
I'd think about some kind of a callback or schema option that allows the developer to inject arbitrary function to be invoked before/after each resolver. Then you could do a lot more things than just metrics. I get the idea, however, I do not like this implementation. I don't want to make this method public, because then people will use it and we'll have to keep it backwards compatible. Minimal API interface is better. I'll think about some kind of solution to this problem.
In most projects where I've used this library I have it as a gateway in front of a system where each resolver invokes a microservice over gRPC. In that setup my metrics are usually on the gRPC client/server layer as middleware. I'll try to think of some kind of a middleware for GraphQL resolvers as well. In the mean time I'll close this issue because the implementation is not correct in my opinion.

**Comment by pavelnikolov** [comment]
@zhaogaolong what is your use case and why do you want this information exposed? Could you, please, raise a separate issue?
