### ISSUE TITLE
how to transfer  context from root resolver to child resolver ?

### ISSUE THREAD

**Issue by invisibleDesigner** [graph-gophers/graphql-go#394]
in root resolver function, I handle some data, and this data need to transfer to child resolver for handle, so I want to save these data in context and transfer it to child resolver function.
but in child resolver function, I only can get context from gin context, no root resolver. is it the design?

**Comment by pavelnikolov** [comment]
I am not sure how to help you without any code snippet. The request context gets propagated through all resolvers if you use it as the first argument in your resolver function. You can easily pass data through struct fields as well. As far as I understand this problem is not directly related to the library. I am closing this issue for now. Feel free to post a question in the gophers slack in the #graphql channel.
