### ISSUE TITLE
graphql.Time unmarshal time check

### ISSUE THREAD

**Issue by EchoUtopia** [graph-gophers/graphql-go#432]
i use graphq.Time as a insert data field, when the front end makes a mistake, and pass the unix time in millisecond, the unmarshaled time will be tens thousands years in the future, like: `55055-03-02 08:00:00+00`. in time.MarshalJSON, the max year is limited to 9999.

so it's a good idea to check the time max limit when parsing

**Comment by panikgaul** [comment]
@EchoUtopia I think this issue can be closed, because the check are already implemented?

I tested it now:

> err := t.UnmarshalGraphQL("55055-03-01T15:04:05Z")
>    if err != nil {
>       fmt.Println(err)
>    }

`parsing time "55055-03-01T15:04:05Z" as "2006-01-02T15:04:05Z07:00": cannot parse "5-03-01T15:04:05Z" as "-"`

**Comment by EchoUtopia** [comment]
@panikgaul sorry that i did not describe clearly.

the function `UnmarshalGraphQL` also accepts `int64`, `int32`, `float64` input type, so when the input is a unexpected large number, graphql-go will assume it's a normal time.

for example: 

```
	gt := &graphql.Time{}
	err := gt.UnmarshalGraphQL(time.Now().UnixNano())
	if err != nil {
		fmt.Println(err)
	}
	fmt.Println(gt)

```

**Comment by pavelnikolov** [comment]
I verified several other unix timestamp converters and they all behave the same way. Since it is supposed to count number of seconds since Jan 1 1970 it is totally normal that the year is in tens of thousands for large numbers. We don't know how people use this library so we do not want to limit them just to year 9999. It would be up to each developer to make sure that they validate both on the client and server sides.

**Comment by panikgaul** [comment]
I tried to fix this issue here: https://github.com/graph-gophers/graphql-go/pull/438

**Comment by EchoUtopia** [comment]
@pavelnikolov that make sense,  but in the other way, it's still a little weird, successfully unmarshaled time can not be marshaled, it's not consistent
