### ISSUE TITLE
Would this change be accepted as a pr?

### ISSUE THREAD

**Issue by TroyDota** [graph-gophers/graphql-go#445]
I made a working version of a root resolver 
https://github.com/StreamerVods/graphql-go

`d-master` branch
Solves the issue of evil-recursive queries or the 1 to many relationship problem.
or allows you to share data between resolvers.

```gql
query {
  animals {
    name
    owner {
      animals {
        owner {
          animals {
            name
          }
        }
      }
    }  
  }
}
```

```go
func MakeResolver(ctx context.Context, vars map[string]interface{}) *rootResolver {
    spew.Dump(generateSelectedFieldMap(ctx))
    spew.Dump(vars)
    return &rootResolver{}
}

type rootResolver struct{}

func (*rootResolver) Query(ctx context.Context) *queryResolver {
    spew.Dump(generateSelectedFieldMap(ctx))
    return &queryResolver{}
}

func makeGQL() {
  schema := graphql.MustParseSchema(s, resolvers.MakeResolver, graphql.UseFieldResolvers())
}
```

That branch allows you to pass a function to create a root resolver at runtime which allows you to query all fields at the root rather than in each resolver.

It also includes this commit https://github.com/StreamerVods/graphql-go/commit/379b9c062e58c1ac2415f44fff31e9a4303deaac
which is from https://github.com/keithmattix/graphql-go and was code added to be able to get query fields on context.

**Comment by TroyDota** [comment]
This also works entirely with current code and has NO breaking changes.

**Comment by pavelnikolov** [comment]
@TroyDota I'm not 100% sure that I completely understand the problem you are trying to solve. Can you, please, explain a little better.

**Comment by TroyDota** [comment]
The change I added allows you to know at the entry what values are required to complete the request. So you can fetch everything at once rather than doing multiple queries

**Comment by pavelnikolov** [comment]
Ok, I understand now. As I've said before, this is the most requested feature ever. I want to add it to the library. I'm just not completely sure on the best way to do it. Back to your original question in the title - yes, this feature is more than welcome as a PR - I'm just not sure about the implementation. There are two main ideas that I'm thinking about - an additional argument in the resolvers which shows the nested fields and their nested fields and arguments. The other options is through the context. There is a 3rd option, which would change (optionally, of course, not to introduce a breaking change) the signature opt-in with a graphql request object. That would contain arguments, directives, selected fields and other nice things in future, so that we don't have to add more arguments. Instead we'd be adding fields to the request struct.

It is high time that this feature gets added in the library.

**Comment by pavelnikolov** [comment]
I'm closing this issue as a duplicate. The selected fields of a query has already been requested and will definitely be included in the library.
