### ISSUE TITLE
I want the client to pass me an array, but I don't see any documentation on how to define an array to accept

### ISSUE THREAD

**Issue by coderYarn** [graph-gophers/graphql-go#487]
I want the client to pass me an array, but I don't see any documentation on how to define an array to accept

**Comment by tonyghita** [comment]
That might look something like this in GraphQL Schema Definition Language (SDL for short):
```graphql
type Query {
  thingsByIDs(ids: [ID!]!): [Thing]!
}
```

And the resolver would look something like

```go
type ThingsByIDsArgs struct {
  IDs []graphql.ID
}

func (r *QueryResolver) ThingsByIDs(ctx context.Context, args *ThingsByIDsArgs) ([]*ThingResolver, error) {
  reutrn nil, errors.New("not yet implemented")
}
```

**Comment by coderYarn** [comment]
think your answer

**Comment by coderYarn** [comment]
![image](https://user-images.githubusercontent.com/63692983/147870426-2fb5c1b7-27b3-40ab-8f2c-36e2915f4934.png)
![image](https://user-images.githubusercontent.com/63692983/147870435-43472728-217d-424b-aa8d-a0af2d9b21c1.png)
How do I define this to receive an array?

**Comment by tonyghita** [comment]
You need to make an input type to represent the elements in the list, and then you take a list of that type. 

We define an input type `Option` with fields `name` and `value` below. Then, we give the `things` field an `options` argument which takes a list of `Option`.

```graphql
input Option {
  name: String!
  value: String!
}

type Query {
  things(options: [Option!]): [Thing!]!
}
```

The corresponding Go code would look very similar to the previous example I posted.

```go
type Option struct {
  Name string
  Value string
}

type ThingsArgs struct {
  Options *[]Option
}

func (r *QueryResolver) Things(ctx context.Context, args *ThingsArgs) ([]*ThingResolver, error) {
  reutrn nil, errors.New("not yet implemented")
}
```

However, this _might_ not be the best schema design since we are removing any kind of "hints" the client might use to discover _what_ the options to the field are by using a String key-value pair to represent the options.

Depending on your use case and how much you can control the schema, a better option might be to create an option input type that explicitly lists the options available for the field instead of using a list. You can also set and communicate default values on input type fields to make it clearer to your clients what the actual valid option names and values are. 

```graphql
input Option {
  useList: Boolean! = false
  sort: Direction! = ASCENDING
  limit: Int! = 10
  someOtherOption: String
}
```

**Comment by pavelnikolov** [comment]
@coderYarn I am closing this issue as it seems to be a question, rather than an issue with the library. What is more @tonyghita has answered your questions. Feel free to reopen it if you have any problems.
You are not the first person to ask this question so it might be a good idea to create an example illustrating that.
