### ISSUE TITLE
New release with directive support

### ISSUE THREAD

**Issue by Asaf51** [graph-gophers/graphql-go#644]
Hi,
I'd like to know if there is a plan to release a new version with the directive support soon?
And also, are there any bugs left to solve or features that are missing?
Thanks!

**Comment by pavelnikolov** [comment]
Directives are the very reason this release is taking so long. I am not happy with the current implementation and would like a redesign that would be similar to a visitor pattern. Actually, I was considering, removing the directives support in order to release `v1.6` and focus mainly on directives for the following version release.
